
version: 2

models:

  - name: gld_dim_author
    description: "Dimension layer of authors"
    columns:
      - name: id
        description: Id of author
      - name: author_name
        description: Name of author

  - name: gld_dim_book
    description: "Dimension layer of books"
    columns:
      - name: id
        description: Id of book
      - name: title
        description: Book title
      - name: description
        description: Description of book
      - name: image
        description: Url for book cover
      - name: preview_link
        description: Link to access this book on google Books
      - name: published_date
        description: The date of publish
      - name: publisher_id
        description: Publisher of book
      - name: info_link
        description: Link to get more information about the book on google Books

  - name: gld_dim_book_author
    description: "Relationship between book and author"
    columns:
      - name: book_id
        description: Id of book
      - name: author_id
        description: Id of author

  - name: gld_dim_book_category
    description: "Relationship between book and category"
    columns:
      - name: book_id
        description: Id of book
      - name: category_id
        description: Id of category

  - name: gld_dim_category
    description: "Dimension layer of categories"
    columns:
      - name: id
        description: Id of author
      - name: category_name
        description: Name of category

  - name: gld_dim_publisher
    description: "Dimension layer of publishers"
    columns:
      - name: id
        description: Id of publisher
      - name: publisher_name
        description: Name of publisher

  - name: gld_dim_review
    description: "Dimension layer of reviews"
    columns:
      - name: id
        description: Id of review
      - name: helpfulness
        description: Helpfulness rating of the review, e.g. 2/3
      - name: score
        description: Rating from 0 to 5 for the book
      - name: review_summary
        description: The summary of text review
      - name: review_text
        description: The full text of a review

  - name: gld_dim_user
    description: "Dimension layer of users"
    columns:
      - name: id
        description: Id of user
      - name: username
        description: Name of user who rate the book

  - name: gld_fact_review
    description: "Fact table of reviews"
    columns:
      - name: id
        description: Id of review
      - name: user_id
        description: Foreign key to dim_user
      - name: book_id
        description: Foreign key to dim_book
      - name: review_time
        description: Time of given the review