duckdb_dbt_azure:
  outputs:
    dev:
      type: duckdb
      path: datalake/dbt/test.duckdb
      threads: 1

    prod:
      type: duckdb
      path: datalake/dbt/test.duckdb
      threads: 1

  target: dev