duckdb_dbt_azure:
  outputs:
    dev:
      type: duckdb
      path: /tmp/books.duckdb
      threads: 1
      schema: dbt
      extensions:
        - parquet
      filesystems:
        - fs: abfs
          anon: false
          account_name: "{{ env_var('STORAGE_ACCOUNT_NAME') }}"
          account_key: "{{ env_var('STORAGE_ACCOUNT_KEY') }}"

  target: dev