name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install project
        run: make install
      - name: Run linter
        run: make lint